// Curated from the bundled MCCC reference and the attributed in-game observations.
// Choice labels live in the controls; retain behavior, exceptions, and dependencies
// here, including explanations that a choice label alone cannot communicate.
export const settingDescriptions: Record<string, string> = {
  AgeStopHuman: 'Stop aging for human, non-occult Sims while they are in the selected age spans. Birthday cakes cannot age them up; use a manual age change such as MCCC’s Set Age command or a console cheat.',
  Autosave_IntervalType: 'Choose how autosaves are scheduled. Pre-Midnight Alarm saves before midnight each Sim night, before MCCC’s alarms run, and ignores Interval Amount.',

  Appearance_ApplyTemplate: 'Choose when to apply appearance templates. Manual applies them only through the MC CAS Sim menu. On age-up applies a template when a Sim enters an age covered by it and is the more efficient automatic option. On zone-in reapplies templates to every Sim entering the current zone, even if already applied, and takes more processing.',
  Appearance_DefaultWalkstyle_AF: 'Set the walkstyle for newly generated adult female Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing adult female Sims too.',
  Appearance_DefaultWalkstyle_AM: 'Set the walkstyle for newly generated adult male Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing adult male Sims too.',
  Appearance_DefaultWalkstyle_EF: 'Set the walkstyle for newly generated elder female Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing elder female Sims too.',
  Appearance_DefaultWalkstyle_EM: 'Set the walkstyle for newly generated elder male Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing elder male Sims too.',
  Appearance_DefaultWalkstyle_TF: 'Set the walkstyle for newly generated teen female Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing teen female Sims too.',
  Appearance_DefaultWalkstyle_TM: 'Set the walkstyle for newly generated teen male Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing teen male Sims too.',
  Appearance_DefaultWalkstyle_YAF: 'Set the walkstyle for newly generated young adult female Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing young adult female Sims too.',
  Appearance_DefaultWalkstyle_YAM: 'Set the walkstyle for newly generated young adult male Sims. It also applies on aging into this group when Change Walkstyles on Age-up is enabled. Changing this in MCCC’s in-game menu updates existing young adult male Sims too.',

  Cleaner_CleanRelationships: 'Choose whose relationships MC Cleaner can remove; family relationships are always kept. Changing this choice preserves the saved cleaning level. Scores use absolute values: a custom level of 20 removes relationships from −20 through 20.',
  Cleaner_CleanPetRelationships: 'Remove pet relationships at or below the selected strength, using absolute scores. For example, a custom level of 25 removes scores from −25 through 25. Zero Level Relationships removes only scores of 0.',
  Dresser_FacialHairAges: 'Add facial hair when male Sims age into the selected stages and have none already. Existing facial hair is never removed. Add facial hair to MC Dresser’s Include List for each selected age; scripts cannot force CAS to generate it, so the list supplies hair when CAS does not.',
  Dresser_MakeupAges: 'During makeup cleaning, Sims of these ages can receive makeup from MC Dresser’s Include Lists. Makeup is removed from Sims of unselected ages.',
  Dresser_MakeupGenders: 'During makeup cleaning, Sims of these genders can receive makeup from MC Dresser’s Include Lists. Makeup is removed from Sims of unselected genders.',
  Dresser_MakeupOutfits: 'Choose which outfit categories Run Makeup Check can change.',
  Dresser_RunOnAgeUp: 'Run MC Dresser’s outfit cleaning when Sims age into the selected stages.',
  Dresser_ReplaceSituationOutfits: 'Replace randomly generated NPC situation outfits with a chosen outfit category for each situation. Keep situation outfit leaves that situation without an override.',

  Inherit_Sim_Type: 'Choose which Sims leave money when they die. Their share of household funds goes to an eligible spouse or is divided equally among their children, including children in other households. Other adults retain their shares of the household funds.',
  Pay_Child_Support_Type: 'Add child support to the active household’s weekly bills for each child aged Teen or younger living elsewhere. Payments depend on the paying Sim’s lot value and are reduced by the Frugal trait. The married or unmarried restriction applies to the child’s parents for both payments and earnings.',

  Marriage_DaysToRun: 'Choose when scheduled random marriage checks run. With no days selected, MCCC uses its built-in schedule based on aging speed.',
  Marriage_ManualRenameSpouses: 'Show a dialog to choose either spouse’s surname after eligible non-active marriages. Either spouse being played qualifies for Played households. The surname rules may also offer a random choice or no change. Closing the dialog with X or Escape leaves both names unchanged. Active households and EA Sims with special system-defined names are excluded; Ancestral Homes use their own naming rules and show no dialog.',
  Marriage_OccupancyType: 'Limit potential spouses by housing status. Prefer Sims with homes tries eligible housed Sims first, then homeless Sims. Homeless only produces no marriages if no eligible homeless spouse is available.',
  Marriage_RenameOppositeSex: 'Choose which surname an opposite-sex couple uses when MC Pregnancy marries them. Random name or no change chooses between either spouse’s surname and leaving both unchanged.',
  Marriage_SameNeighborhood: 'Limit marriage partners by world. Always blocks cross-world marriages even for established couples. Prefer allows existing boyfriend/girlfriend or engaged couples across worlds, but other matches must share a world. Never Limit Partners by Neighborhood ignores where they live.',
  Marriage_SpouseGenders: 'Choose eligible spouse genders when Same-Sex Percentage is greater than zero.',
  Marriage_SpouseSimAges: 'Choose ages eligible to be selected as a spouse. Teen eligibility requires the MC WooHoo module.',
  Marriage_TargetSimAges: 'Choose ages eligible for random marriage checks. Teen eligibility requires the MC WooHoo module.',

  Occult_AlienFrequency: 'Control alien contact results, including abductions, visits, and phone calls. No abductions keeps the satellite’s Contact option unavailable and Prevent Abductions active once chosen. Normal uses EA’s rules. High increases abductions and visits and keeps Contact available. Alien invasion allows almost constant abductions, limited by Time Between Abductions.',
  Occult_AlienPollinatorGenders: 'Choose the gender of the next generated alien pollinator. Only one exists at a time; changing this does not replace an existing pollinator.',
  Occult_ForceAlienDisguiseType: 'Choose whether aliens enter lots disguised or undisguised. Default follows EA’s rules. Aliens always remove their disguises on the alien homeworld, regardless of this choice.',
  Occult_OccultTypeMaximumAge: 'Choose the age at which each occult species stops normal aging. Normal aging continues through all ages. Vampires default to Young Adult; other occult species default to Normal aging.',

  Population_BarNights: 'Choose themed bar nights that can send invitations and announcements. Unselected nights stop these messages, but themed NPCs still appear if an active Sim is at a bar at 8 PM on that night.',
  Population_ButlerAges: 'Choose eligible butler ages, including Teen and Young Adult in addition to EA’s usual Adult and Elder.',
  Population_DisableImmortalSims: 'Let selected groups of normally immortal Sims age and die. City Living includes the Love Guru, City Repair Sims, Weirdos, and Busker Statues; Get To Work includes the alien pollinator and detective-career criminals; Service Sims includes nannies and butlers; Seasons includes scarecrows.',
  Population_ImportSimNameChoice: 'Handle name collisions when importing library Sims. Skip rejects imports whose name already exists. Always keeps the imported name even on duplicates. Use Non-Duplicate Name keeps the imported name only when unique; otherwise it keeps the generated Sim’s name. Never Use Import Name keeps the generated Sim’s name. Only Skip prevents repeated imports through this name check; the other choices can import the same Sim more than once.',
  Population_MoveOutEldersType: 'Move elders from non-active households into shared retirement households without leaving dependents alone. More retirement households are used when one fills up. Non-Ancestral excludes elders in Ancestral Homes.',
  Population_NumAdjustLot: 'Apply Maximum Sims in Zone as the Sim limit for the selected lots and situations.',
  Population_RandomChallengeLotType: 'Choose which lots can receive random lot challenges.',
  Population_RandomChallengeTimeUnits: 'Choose the unit for Maximum Challenge Frequency. Allow enough time for challenges to take effect; some develop more slowly during gameplay.',
  Population_RandomLimitHouseholdType: 'Limit which saved library households supply imported Sims, based on whether you or another player created them.',
  Population_UseTagsOnImportSims: 'Filter households used to replace randomly generated Sims by tags in their descriptions. Limit Bypass Tags excludes #mccc_bypass; Only Limit Tag requires #mccc_include. Disabled skips reading descriptions for faster processing. These filters do not hide households from manual copy/paste import menus.',

  Pregnancy_AdoptionAges: 'For adoptions produced by random pregnancy checks, choose the child’s age randomly from the selected stages.',
  Pregnancy_AllowMalePregnancy: 'Control male pregnancy during scheduled random NPC pregnancy checks. Same sex only requires a male partner. WooHoo and Try for Baby use separate settings.',
  Pregnancy_DaysToRun: 'Choose when scheduled random pregnancy checks run. With no days selected, MCCC uses its built-in schedule based on aging speed.',
  Pregnancy_InsiminateGenders: 'Choose eligible pregnancy-partner genders when the Same-Sex Percentage roll is not met.',
  Pregnancy_NameInactiveAdoption: 'Choose whose adoptions trigger naming dialogs, including non-active households after random pregnancy-adoption results. Related to Active Household includes children adopted by Sims related to an active Sim.',
  Pregnancy_NameInactiveOffspring: 'Choose whose births trigger baby naming dialogs beyond the active household. Related to Active Household includes births to relatives of active Sims and babies whose parents are an NPC and an active Sim.',
  Pregnancy_OccupancyType: 'Limit potential pregnancy partners by housing status. Prefer Sims with homes tries eligible housed Sims first, then homeless Sims. Homeless only produces no pregnancies if no eligible homeless partner is available.',
  Pregnancy_OffspringGender: 'Choose which genders offspring can have.',
  Pregnancy_OffspringTraitsType: 'Choose how offspring inherit traits. Maximum uses the configured limit, or fewer if not enough valid traits are available. Random chooses between one and that limit. Inherit no Traits disables trait inheritance.',
  Pregnancy_PauseSimsPregnancy: 'Immediately stop pregnancy progression for selected groups. Selecting none leaves only pregnancies paused individually through MCCC paused. Pause on Playable Labor is separate: it lets pregnancy reach labor, then shows a delivery dialog.',
  Pregnancy_PetAgeToRun: 'Choose pet ages eligible for random pregnancies. Using only Elder is best suited to long elder lifespans, so parents do not die while their offspring are still very young.',
  Pregnancy_RelationshipOnly: 'Limit pregnancy partners by their existing relationship; all other pregnancy criteria still apply. Significant Other also includes married couples. WooHoo partners additionally includes any pair that has previously had WooHoo.',
  Pregnancy_SeedSimAges: 'Choose ages eligible to be selected as a pregnancy partner. Teen eligibility requires the MC WooHoo module.',
  Pregnancy_TargetSimAges: 'Choose ages eligible for random pregnancy checks. Teen eligibility requires the MC WooHoo module.',

  RelationshipCullingType: 'Choose how unused relationships are removed. The MC Cleaner option replaces EA’s culling with your configured cleaning rules and requires MC Cleaner. Restart the game after changing this setting.',
  Show_DeathNotificationType: 'Show a notification when a Sim dies, for the selected audience.',
  Show_PetPregnancyNotificationType: 'Show a notification when a pet becomes pregnant, for the selected audience.',
  Show_Sim_Menu_Type: 'Choose where MCCC menus appear. Shift-only options show menus only while Shift is held.',
  Silence_Phone_Texts: 'Choose which texts active Sims can receive while their phone is silenced.',

  Woohoo_NudeWoohooGender: 'Choose which genders can become nude for WooHoo. With none selected, no Sims qualify.',
  Woohoo_NudityAges: 'Choose which ages can become nude for WooHoo. With none selected, no Sims become nude through this setting for any type of WooHoo.',
  Woohoo_OppositeSexPregnantSim: 'Choose who can become pregnant from male/female Try for Baby or Risky WooHoo. Target receives the interaction; Initiator starts it. Gender and interaction-role choices can be combined, but using one basis is easier to predict.',
  Woohoo_SameSexPregnantSim: 'Choose who can become pregnant from same-sex Try for Baby. Target receives the interaction; Initiator starts it. Selecting both allows both Sims to become pregnant.',
}
